### ISSUE TITLE
Questions about R version in this research

### ISSUE THREAD

**Issue by HelloWorldLTY** [shbrief/GenomicSuperSignature#21]
Hi, I tried to run the codes related to RAV model building and met errors related to package installation. My R version is 4.1.3.
![image](https://user-images.githubusercontent.com/43333475/177456883-40af39b9-c899-45c3-90f9-a07c87401df9.png)
For the GF package, I cannot install it based on my R. Therefore, could you please share the version of your software? Thanks a lot.

**Comment by shbrief** [comment]
@HelloWorldLTY 
I'm using R 4.2.1. Btw, which script are you running? I can take a look at it as well. Thanks!

**Comment by HelloWorldLTY** [comment]
It happens in 01_import.R. I need to install Genomic Feature. Thanks a lot.

**Comment by shbrief** [comment]
Great! The codes under my model_building repository are mostly for in-house use, but if you have any questions, let me know. FYI, I plan to implement the RAVmodel building process in the cloud-based genomics platform in the future - probably not soon, but once it happens, will be posted. ;) Thanks.
