### ISSUE TITLE
Some questions about using Pathway convergence

### ISSUE THREAD

**Issue by HelloWorldLTY** [shbrief/GenomicSuperSignature#24]
Hi, I find that using the codes given in the readme file, the installation process of GSSP will fail.
![image](https://user-images.githubusercontent.com/43333475/179538751-49231486-f02b-488b-8287-f776b4cc3b9f.png)
The error looks like this. Could you please help me resolve it? Thanks a lot!

**Comment by shbrief** [comment]
shbrief/GenomicSuperSignaturePaper@64478d4ed42c0e318fedece8e1aaf3feeaf3c130
